services:
  web:
    build:
      target: dev
    ports:
      - '5173:5173'
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: sync
          path: ./
          target: ./web
          ignore:
            - ./node_modules
